# Generated by Django 5.0.3 on 2024-03-15 16:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dall_e_prompt', models.CharField(default='Draw 3 circles', max_length=100000, verbose_name='DALL-E prompt to generate image')),
                ('dall_e_model', models.CharField(default='dall-e-3', max_length=100, verbose_name='DALL-E model')),
                ('dall_e_size', models.CharField(default='1024x1024', max_length=100, verbose_name='Image size')),
                ('dall_e_quality', models.CharField(choices=[('standard', 'Standard'), ('hd', 'hd')], default='standard', max_length=50, verbose_name='Image quality')),
                ('dall_e_n', models.IntegerField(default=1, verbose_name='n')),
                ('chatgpt_api_key', models.CharField(default='', max_length=100, verbose_name='Chatgpt api key')),
                ('chat_gpt_temperature', models.IntegerField(default=0, verbose_name='temperature')),
                ('chat_gpt_top_p', models.IntegerField(default=1, verbose_name='top_p')),
                ('chat_gpt_frequency_penalty', models.IntegerField(default=0, verbose_name='frequency_penalty')),
                ('chat_gpt_presence_penalty', models.IntegerField(default=0, verbose_name='presence_penalty')),
                ('chat_gpt_max_tokens', models.IntegerField(default=1000, verbose_name='presence_penalty')),
                ('suggest_changes_prompt', models.CharField(default='What do you think it is better change in this image? Make your suggestions as prompt to dalle 3. Provide only suggestions as not numbered list and without any other text.', max_length=10000, verbose_name="'Suggest changes' prompt")),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dalle_request', models.CharField(max_length=100000, verbose_name='DALL-E prompt to generate image')),
                ('dalle_response', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/nikos/data'), upload_to='')),
                ('suggest_changes_request', models.CharField(max_length=10000, verbose_name="'Suggest changes' request")),
                ('suggest_changes_response', models.CharField(max_length=50000, verbose_name="'Suggest changes' response")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
            },
        ),
    ]
