# Generated by Django 5.0.3 on 2024-03-21 17:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatgpt_api_key', models.TextField(default='', max_length=100, verbose_name='Chatgpt api key')),
                ('chat_gpt_temperature', models.IntegerField(default=0, verbose_name='temperature')),
                ('chat_gpt_top_p', models.IntegerField(default=1, verbose_name='top_p')),
                ('chat_gpt_frequency_penalty', models.IntegerField(default=0, verbose_name='frequency_penalty')),
                ('chat_gpt_presence_penalty', models.IntegerField(default=0, verbose_name='presence_penalty')),
                ('text_image_feedback_spiral_chat_gpt_max_tokens', models.IntegerField(default=1000, verbose_name='Text-image feedback spiral max_tokens')),
                ('dall_e_prompt', models.TextField(default='Draw 3 circles', max_length=100000, verbose_name='DALL-E prompt to generate image')),
                ('dall_e_model', models.TextField(default='dall-e-3', max_length=100, verbose_name='DALL-E model')),
                ('dall_e_size', models.TextField(default='1024x1024', max_length=100, verbose_name='Image size')),
                ('dall_e_quality', models.TextField(choices=[('standard', 'Standard'), ('hd', 'hd')], default='standard', max_length=50, verbose_name='Image quality')),
                ('dall_e_n', models.IntegerField(default=1, verbose_name='n')),
                ('suggest_changes_prompt', models.TextField(default='What do you think it is better change in this image? Make your suggestions as prompt to dalle 3. Provide only suggestions as not numbered list and without any other text.', max_length=20000, verbose_name="'Suggest changes' prompt")),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dalle_request', models.TextField(max_length=100000, verbose_name='DALL-E prompt to generate image')),
                ('dalle_response', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/nikos/data'), upload_to='')),
                ('suggest_changes_request', models.TextField(max_length=20000, verbose_name="'Suggest changes' request")),
                ('suggest_changes_response', models.TextField(max_length=10000, verbose_name="'Suggest changes' response")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('key_field', models.CharField(default='', max_length=250, primary_key=True, serialize=False)),
                ('value', models.TextField(default='', max_length=100000)),
            ],
            options={
                'indexes': [models.Index(fields=['key_field'], name='app_keyvalu_key_fie_a324c3_idx')],
            },
        ),
    ]
