# Generated by Django 5.0.3 on 2024-03-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='current_tab',
            field=models.CharField(default='text_image_feedback_spiral', max_length=100, verbose_name='Current tab'),
        ),
    ]
