# Generated by Django 5.0.3 on 2024-03-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_config_chat_gpt_max_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='selected_video',
            field=models.CharField(default='', max_length=3000, verbose_name='Selected video'),
        ),
    ]
