# Generated by Django 5.0.3 on 2024-04-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_config_chat_gpt_frequency_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='chatgpt_api_key',
            field=models.CharField(blank=True, default='', help_text="Can be found <a target='_blank' href='https://platform.openai.com/api-keys'>here</a>", max_length=100, verbose_name='OpenAI api key'),
        ),
    ]
