# Generated by Django 5.0.3 on 2024-04-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_config_chat_gpt_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='chat_gpt_temperature',
            field=models.FloatField(default=2, help_text='\n        What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random,\n        while lower values like 0.2 will make it more focused and deterministic.\n<br>\nWe generally recommend altering this or top_p but not both.\n        ', verbose_name='temperature'),
        ),
    ]
