# Generated by Django 5.0.3 on 2024-04-05 23:13

from django.db import migrations

from app.models import Config


def forward_func(apps, schema_editor):
    config = Config.objects.all().first()
    config.chat_gpt_temperature = 1.0
    config.chat_gpt_top_p = 1.0
    config.chat_gpt_frequency_penalty = 0
    config.chat_gpt_presence_penalty = 0
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_config_chat_gpt_temperature'),
    ]

    operations = [
        migrations.RunPython(
            code=forward_func,
        ),
    ]


