# Generated by Django 5.0.3 on 2024-04-05 23:13

from django.db import migrations


def forward_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_config_chat_gpt_temperature'),
    ]

    operations = [
        migrations.RunPython(
            code=forward_func,
        ),
    ]


