# Generated by Django 5.0.3 on 2024-04-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20240405_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='claude_temperature',
            field=models.FloatField(default=1, help_text='Amount of randomness injected into the response.\nRanges from 0.0 to 1.0. Use temperature closer to 0.0 for analytical / multiple choice, and closer to 1.0 for creative and generative tasks.\n\nNote that even with temperature of 0.0, the results will not be fully deterministic.\n        ', verbose_name='temperature'),
        ),
    ]
