# Generated by Django 5.0.3 on 2024-04-05 23:26

from django.db import migrations

from app.models import Config


def forward_func(apps, schema_editor):
    config = Config.objects.all().first()
    config.claude_temperature = 1.0
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_config_claude_temperature'),
    ]

    operations = [
        migrations.RunPython(
            code=forward_func,
        ),
    ]
