# Generated by Django 5.0.3 on 2024-04-12 16:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20240405_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='dall_e_quality',
            field=models.CharField(choices=[('standard', 'standard'), ('hd', 'hd')], default='standard', max_length=100, verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='config',
            name='dall_e_size',
            field=models.CharField(choices=[('1024x1024', '1024x1024'), ('1792x1024', '1792x1024'), ('1024x1792', '1024x1792')], default='1024x1024', max_length=100, verbose_name='Image size'),
        ),
        migrations.AddField(
            model_name='config',
            name='dall_e_style',
            field=models.CharField(choices=[('vivid', 'vivid'), ('natural', 'natural')], default='vivid', help_text='The style of the generated images. Must be one of vivid or natural. \n        Vivid causes the model to lean towards generating hyper-real and dramatic images.\n        Natural causes the model to produce more natural, less hyper-real looking images. ', max_length=100, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='step',
            name='dalle_request',
            field=models.TextField(default='Draw 3 circles', max_length=100000, verbose_name='DALL-E prompt to generate image'),
        ),
        migrations.AlterField(
            model_name='step',
            name='dalle_response',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/nikos/media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='step',
            name='suggest_changes_request',
            field=models.TextField(default='What do you think it is better change in this image? Make your suggestions as prompt to dalle 3.\nProvide only suggestions as not numbered list and without any other text.', max_length=20000, verbose_name="'Suggest changes' request"),
        ),
    ]
