# Generated by Django 5.0.3 on 2024-04-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_config_dall_e_quality_config_dall_e_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='dall_e_show_last_images',
            field=models.IntegerField(default=5, verbose_name='Show last images'),
        ),
        migrations.AlterField(
            model_name='config',
            name='dall_e_quality',
            field=models.CharField(choices=[('standard', 'standard'), ('hd', 'hd')], default='standard', help_text='The quality of the image that will be generated.\n         hd creates images with finer details and greater consistency across the image.', max_length=100, verbose_name='Quality'),
        ),
    ]
