# Generated by Django 5.0.3 on 2024-04-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_config_dall_e_show_last_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='revised_prompt',
            field=models.TextField(default='', help_text='The prompt that was used to generate the image, if there was any revision to the prompt.', max_length=100000, verbose_name='Revised DALL-E prompt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='dalle_request',
            field=models.TextField(max_length=100000, verbose_name='DALL-E prompt to generate image'),
        ),
        migrations.AlterField(
            model_name='step',
            name='suggest_changes_request',
            field=models.TextField(max_length=20000, verbose_name="'Suggest changes' request"),
        ),
    ]
