# Generated by Django 5.0.3 on 2024-04-13 16:19

from django.db import migrations
from app.utils import get_config_sync


def forward_func(apps, schema_editor):
    config = get_config_sync()
    config.chat_gpt_temperature = 1.0
    config.chat_gpt_top_p = 1.0
    config.chat_gpt_frequency_penalty = 0
    config.chat_gpt_presence_penalty = 0
    config.claude_temperature = 1.0
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_step_revised_prompt_alter_step_dalle_request_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=forward_func,
        ),
    ]
