# Generated by Django 5.0.3 on 2024-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_word_word_word_lemma_word_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordFreqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('lemma', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('part_of_speech', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='word',
            options={},
        ),
        migrations.RemoveField(
            model_name='word',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='word',
            name='source_file',
            field=models.CharField(max_length=200),
        ),
    ]
