# Generated by Django 5.0.3 on 2024-09-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_wordfreqs_alter_word_options_remove_word_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordfreqs',
            name='year',
        ),
        migrations.AddField(
            model_name='wordfreqs',
            name='source_file',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
