# Generated by Django 5.0.3 on 2024-09-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_wordfreqs_source_file_wordfreqs_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(max_length=10)),
                ('black_or_white', models.CharField(max_length=10)),
                ('set_by', models.CharField(max_length=10)),
            ],
        ),
    ]
