# Generated by Django 5.0.3 on 2024-09-06 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_lists_frequencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='part_of_speech',
        ),
    ]
