# Generated by Django 5.0.3 on 2024-09-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_lists_part_of_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='frequencies',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
