# Generated by Django 5.0.3 on 2024-09-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_lists_frequencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='source_file',
            field=models.TextField(max_length=2000),
        ),
    ]
