# Generated by Django 5.0.3 on 2024-09-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_word_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='lemma',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='lemma',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='original',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='wordfreqs',
            name='lemma',
            field=models.TextField(max_length=1000),
        ),
    ]
